### ISSUE TITLE
Broken links on "Azure SDK for Java libraries" page

### ISSUE THREAD

**Issue by pritamso** [Azure/azure-sdk#3291]
We've found multiple broken links on "Azure SDK for Java libraries" page. I wasn't able to find replacement for the same.

https://docs.microsoft.com/en-us/azure/developer/java/sdk/azure-sdk-library-package-index page.

Here's the list of all broken links -

- https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/signalr/mgmt-v2020_05_01
- https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/netapp/mgmt-v2019_06_01
- https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/datafactory/mgmt-v2018_06_01
- https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/deploymentmanager/mgmt-v2019_11_01_preview
- https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/policyinsights/mgmt-v2019_10_01
- https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/storageimportexport/mgmt-v2016_11_01
- https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/marketplaceordering/mgmt-v2015_06_01
- https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/resourcehealth/mgmt-v2017_07_01
- https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/edgegateway/mgmt-v2019_03_01
- https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/costmanagement/mgmt-v2019_11_01
- https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/vmwarecloudsimple/mgmt-v2019_04_01
- https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/resources/mgmt-v2016_06_01
- https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/cognitiveservices/mgmt-v2017_04_18
- https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/mediaservices/mgmt-v2019_05_01_preview
- https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/authorization/mgmt-v2018_09_01_preview
- https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/subscription/mgmt-v2019_10_01_preview
- https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/powerbidedicated/mgmt-v2017_10_01
- https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/devspaces/mgmt-v2018_06_01_preview
- https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/streamanalytics/mgmt-v2016_03_01
- https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/hanaonazure/mgmt-v2017_11_03_preview
- https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/apimanagement/mgmt-v2019_12_01
- https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/logic/mgmt-v2018_07_01_preview
- https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/postgresql/mgmt-v2017_12_01
- https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/peering/mgmt-v2019_08_01_preview
- https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/storagecache/mgmt-v2020_03_01
- https://github.com/Azure/azure-sdk-for-java/tree/master/profiles/2019-03-01-hybrid
- https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/databox/mgmt-v2019_09_01
- https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/relay/mgmt-v2017_04_01
- https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/maintenance/mgmt-v2018_06_01_preview
- https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/synapse/mgmt-v2019_06_01_preview
- https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/devtestlabs/mgmt-v2018_09_15
- https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/eventhubs/mgmt-v2018_01_01_preview
- https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/parents/azure-arm-parent
- https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/datamigration/mgmt-v2018_07_15_preview
- https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/avs/mgmt-v2020_03_20
- https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/operationsmanagement/mgmt-v2015_11_01_preview
- https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/labservices/mgmt-v2018_10_15
- https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/sqlvirtualmachine/mgmt-v2017_03_01_preview
- https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/machinelearningservices/mgmt-v2019_05_01
- https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/privatedns/mgmt-v2018_09_01
- https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/support/mgmt-v2020_04_01
- https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/hdinsight/mgmt-v2018_06_01_preview
- https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/appconfiguration/mgmt-v2020_06_01
- https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/appplatform/mgmt-v2020_07_01
- https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/managedapplications/mgmt-v2019_07_01
- https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/timeseriesinsights/mgmt-v2017_11_15
- https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/resourcegraph/mgmt-v2019_04_01
- https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/servicefabric/mgmt-v2018_02_01
- https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/mixedreality/mgmt-v2020_05_01
- https://docs.microsoft.com/java/api/overview/azure/spring-boot-starter-servicebus-jms-readme/
- https://docs.microsoft.com/java/api/overview/azure/spring-cloud-stream-binder-servicebus-core-readme/
- https://docs.microsoft.com/java/api/overview/azure/spring-cloud-stream-binder-servicebus-queue-readme/
- https://docs.microsoft.com/java/api/overview/azure/spring-boot-starter-active-directory-b2c-readme/
- https://docs.microsoft.com/java/api/overview/azure/spring-cloud-stream-binder-eventhubs-readme/
- https://docs.microsoft.com/java/api/overview/azure/spring-cloud-messaging-readme/
- https://docs.microsoft.com/java/api/overview/azure/spring-boot-starter-keyvault-secrets-readme/
- https://docs.microsoft.com/java/api/overview/azure/spring-cloud-starter-cache-readme/
- https://docs.microsoft.com/java/api/overview/azure/spring-boot-starter-storage-readme/
- https://docs.microsoft.com/java/api/overview/azure/spring-cloud-stream-binder-test-readme/
- https://docs.microsoft.com/java/api/overview/azure/spring-boot-starter-cosmos-readme/
- https://docs.microsoft.com/java/api/overview/azure/spring-integration-test-readme/
- https://docs.microsoft.com/java/api/overview/azure/spring-boot-starter-keyvault-certificates-readme/
- https://docs.microsoft.com/java/api/overview/azure/spring-cloud-telemetry-readme/
- https://docs.microsoft.com/java/api/overview/azure/spring-boot-starter-active-directory-readme/
- https://docs.microsoft.com/java/api/overview/azure/spring-cloud-stream-binder-servicebus-topic-readme/
- https://docs.microsoft.com/java/api/overview/azure/spring-integration-core-readme/
- https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/iotcentral/mgmt-v2018_09_01

**Comment by weshaggard** [comment]
Most of those I believe have already been fixed with the latest batch fixed with https://github.com/Azure/azure-sdk/pull/3289.

**Comment by weshaggard** [comment]
To get this fixed on the docs site this PR https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/1822 needs to get merged.

**Comment by KarlErickson** [comment]
@pritamso @weshaggard that azure-dev-docs-pr PR has been delayed due to UX studies. I should get the go-ahead to merge it early next week.

**Comment by pritamso** [comment]
@KarlErickson Are you going to merge PR as there are 60+ links still appearing broken on page.

@weshaggard

**Comment by KarlErickson** [comment]
@pritamso @weshaggard I'll find out this afternoon, and hopefully merge by EOD today.
